CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS usuario_db;
CREATE DATABASE IF NOT EXISTS cancha_db;
CREATE DATABASE IF NOT EXISTS horario_db;
CREATE DATABASE IF NOT EXISTS reserva_db;
CREATE DATABASE IF NOT EXISTS pago_db;
